--------------------------------------------------------
--  File created - Tuesday-April-04-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GN_EMPLOYEE_SPONSOR_MASTER
--------------------------------------------------------

  CREATE TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" 
   (	"SPSNSR_ID" NUMBER(18,0), 
	"SPNSR_NAME" VARCHAR2(100 BYTE), 
	"SPSNSR_ADDRESS1" VARCHAR2(150 BYTE), 
	"SPSNSR_ADDRESS2" VARCHAR2(150 BYTE), 
	"SPSNSR_ADDRESS3" VARCHAR2(150 BYTE), 
	"CNTRY_ID" NUMBER(5,0), 
	"ORG_ID" NUMBER(5,0), 
	"SPNSR_DOCNO" NUMBER(10,0), 
	"CORPRT_ID" NUMBER(6,0), 
	"SPSNSR_MOBILE" VARCHAR2(50 BYTE), 
	"SPSNSR_PHONE" VARCHAR2(50 BYTE), 
	"SPSNSR_EMAIL" VARCHAR2(20 BYTE), 
	"SPSNSR_FAX" VARCHAR2(20 BYTE), 
	"SPSNSR_INS_USR_ID" NUMBER, 
	"SPSNSR_INS_DATE" DATE DEFAULT SYSDATE, 
	"SPSNSR_UPD_USR_ID" NUMBER(10,0), 
	"SPSNSR_UPD_DATE" DATE, 
	"SPSNSR_CNCL_USR_ID" NUMBER(10,0), 
	"SPSNSR_CNCL_DATE" DATE, 
	"SPSNSR_CNCL_REASN" VARCHAR2(500 BYTE), 
	"SPSNSR_STATUS" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "COMPZIT_AWMS" ;
 

   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_ID" IS 'Auto increment field. Start number 1.
Use Sequence
';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPNSR_NAME" IS 'This field stores sponsor name. This is unique field.';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_ADDRESS1" IS 'This field stores the sponsor first address.';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_ADDRESS2" IS 'This field stores the sponsor second address.';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_ADDRESS3" IS 'This filed stores the sponsor third address.';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."CNTRY_ID" IS 'Foreign key relation to GN_COUNTRY_MASTER';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."ORG_ID" IS 'Foreign Key Relation To
GN_ORGANIZATIONS
';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPNSR_DOCNO" IS 'This field stores the document number';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."CORPRT_ID" IS 'Foreign Key Relation To
GN_CORP_OFFICES
';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_MOBILE" IS 'This field stores the sponsor mobile number';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_PHONE" IS 'This field stores the sponsor phone number.';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_EMAIL" IS 'This field stores sponsor email address.';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_FAX" IS 'This field stores the Fax number ';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_INS_USR_ID" IS 'Foreign Key Relation To GN_USERS';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_INS_DATE" IS 'This field will store sponsor inserted date.';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_UPD_USR_ID" IS 'Foreign Key Relation To GN_USERS';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_UPD_DATE" IS 'This field will store sponsor modification date.';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_CNCL_USR_ID" IS 'Foreign Key Relation To GN_USERS';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_CNCL_DATE" IS 'This field will store sponsor cancelled date';
 
   COMMENT ON COLUMN "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER"."SPSNSR_CNCL_REASN" IS 'Reason for cancellation should be updated to this field.';
--------------------------------------------------------
--  DDL for Index GN_EMPLOYEE_SPONSOR_MASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER_PK" ON "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ("SPSNSR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "COMPZIT_AWMS" ;
--------------------------------------------------------
--  DDL for Index GN_EMPLOYEE_SPONSOR_MASTE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTE_UK1" ON "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ("SPNSR_NAME", "ORG_ID", "CNTRY_ID", "SPSNSR_CNCL_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "COMPZIT_AWMS" ;
--------------------------------------------------------
--  Constraints for Table GN_EMPLOYEE_SPONSOR_MASTER
--------------------------------------------------------

  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ADD CONSTRAINT "CH_SPNSR_CNCL_REASN" CHECK ((LENGTH(SPSNSR_CNCL_REASN)>=10 AND SPSNSR_CNCL_USR_ID IS NOT NULL) OR
(SPSNSR_CNCL_REASN IS NULL AND SPSNSR_CNCL_USR_ID IS NULL)) ENABLE;
 
  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ADD CONSTRAINT "GN_EMPLOYEE_SPONSOR_MASTER_PK" PRIMARY KEY ("SPSNSR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "COMPZIT_AWMS"  ENABLE;
 
  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ADD CONSTRAINT "GN_EMPLOYEE_SPONSOR_MASTE_UK1" UNIQUE ("SPNSR_NAME", "ORG_ID", "CNTRY_ID", "SPSNSR_CNCL_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "COMPZIT_AWMS"  ENABLE;
 
  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" MODIFY ("SPSNSR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GN_EMPLOYEE_SPONSOR_MASTER
--------------------------------------------------------

  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ADD CONSTRAINT "FK_SPNSR_CNCL_USR_ID" FOREIGN KEY ("SPSNSR_CNCL_USR_ID")
	  REFERENCES "COMPZIT_AWMS"."GN_USERS" ("USR_ID") ENABLE;
 
  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ADD CONSTRAINT "FK_SPNSR_CNTRY_ID" FOREIGN KEY ("CNTRY_ID")
	  REFERENCES "COMPZIT_AWMS"."GN_COUNTRY_MASTER" ("CNTRY_ID") ENABLE;
 
  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ADD CONSTRAINT "FK_SPNSR_CORPRT_ID" FOREIGN KEY ("CORPRT_ID")
	  REFERENCES "COMPZIT_AWMS"."GN_CORP_OFFICES" ("CORPRT_ID") ENABLE;
 
  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ADD CONSTRAINT "FK_SPNSR_INS_USR_ID" FOREIGN KEY ("SPSNSR_INS_USR_ID")
	  REFERENCES "COMPZIT_AWMS"."GN_USERS" ("USR_ID") ENABLE;
 
  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ADD CONSTRAINT "FK_SPNSR_ORG_ID" FOREIGN KEY ("ORG_ID")
	  REFERENCES "COMPZIT_AWMS"."GN_ORGANIZATIONS" ("ORG_ID") ENABLE;
 
  ALTER TABLE "COMPZIT_AWMS"."GN_EMPLOYEE_SPONSOR_MASTER" ADD CONSTRAINT "FK_SPNSR_UPD_USR_ID" FOREIGN KEY ("SPSNSR_UPD_USR_ID")
	  REFERENCES "COMPZIT_AWMS"."GN_USERS" ("USR_ID") ENABLE;
