<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/MasterPageCompzit.master" AutoEventWireup="true" CodeFile="Report_Builder.aspx.cs" Inherits="Report_Builder_Report_Builder" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cphHead" Runat="Server">

    <script src="/css/New%20Plugins/libs/jquery-2.1.1.min.js"></script>
    <script src="/css/New%20Plugins/libs/jquery-ui-1.10.3.min.js"></script>
    <script src="/css/New%20Plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/css/New%20Plugins/datatable-responsive/datatables.responsive.min.js"></script>

    <script src="/css/New%20Plugins/datatable-export/dataTables.buttons.min.js"></script>
    <script src="/css/New%20Plugins/datatable-export/buttons.flash.min.js"></script>
    <script src="/css/New%20Plugins/datatable-export/jszip.min.js"></script>
    <script src="/css/New%20Plugins/datatable-export/pdfmake.min.js"></script>
    <script src="/css/New%20Plugins/datatable-export/vfs_fonts.js"></script>
    <script src="/css/New%20Plugins/datatable-export/buttons.html5.min.js"></script>
    <script src="/css/New%20Plugins/datatable-export/buttons.print.js"></script>

    <link href="/js/New%20js/date_pick/datepicker.css" rel="stylesheet" />
    <script src="/js/New%20js/date_pick/datepicker.js"></script>
  

  
    <script>

        var $noCon = jQuery.noConflict();

        $noCon(window).load(function () {


        });

        $noCon(document).ready(function () {

            LoadDropdowns(0);
            LoadSearch();
            ChangeFilter(0);

            var Heading = document.getElementById("cphMain_spanHead").innerHTML;
           
            var TotalRowCnt = document.getElementById("cphMain_hiddenRowCnt").value;
            var UserName = document.getElementById("cphMain_hiddenUsername").value;
            var Date = document.getElementById("cphMain_hiddenDate").value;
            var TotalRows = document.getElementById("cphMain_hiddenTotalRows").value;

            var Display = '<span style="font-size: 20px;">' + document.getElementById("cphMain_hiddenCorporateName").value + '</span></br>';
            Display += '' + Heading + '<br/>';
            Display += 'Generated By: ' + UserName + '<br/>';
            Display += 'Generated On: ' + Date + '<br/>';
            Display += 'Number of Records: ' + TotalRows + '<br/>';

            var FilterList = LoadPrintFilters();

            if (FilterList != "") {
                Display += 'Filter Value:<br/>' + FilterList + '';
            }

            var BtnsList = "", Btns = "";

            var arr = [];
            if (document.getElementById("cphMain_hiddenDtActns").value != "") {

                var BtnsList = document.getElementById("cphMain_hiddenDtActns").value;
                var temp = new Array();
                temp = BtnsList.split('¦');

                for (a in temp) {
                    if (temp[a] != "") {

                        if (temp[a] == "print") {

                            var PrintList = '<td colspan=' + TotalRowCnt + '>';
                            PrintList += Display;
                            PrintList += '</td>';
                            arr.push({
                                extend: temp[a].toString(),
                                title: Heading,
                                autoPrint: false,
                                className: 'prin_ser',
                                customize: function (win) {
                                    $noCon(win.document.body).find('thead').prepend(PrintList);
                                    if (document.getElementById("cphMain_HiddenFieldHeader").value != "") {
                                        var Search = new Array();
                                        Search = document.getElementById("cphMain_HiddenFieldHeader").value.split('¦');
                                        var cnt = 1;
                                        for (a in Search) {
                                            if (Search[a] != "") {
                                                field = Search[a].split('—');
                                                var colAlign = field[1];
                                                $noCon(win.document.body).find('thead th:nth-child(' + cnt + '),tbody td:nth-child(' + cnt + ')').css('text-align', colAlign);
                                                cnt++;
                                            }
                                        }
                                    }


                                }
                            });
                        }
                        else if (temp[a] == "pdf") {
                            arr.push({
                                extend: temp[a].toString(),
                                title: Heading,
                                orientation: 'landscape',
                                pageSize: 'A4',

                                className: 'pdf_ser',
                                customize: function (doc) {

                                }
                            });
                        }
                        else {
                            arr.push({
                                extend: temp[a].toString(),
                                title: Heading,
                                className: 'word_ser',

                            });
                        }

                    }
                }
            }
            else {
                document.getElementById("divPrint").style.display = "block";
            }

            $noCon('#ReportTable').DataTable({
                dom: 'lBfrtip',
                buttons: arr,
              
                exportOptions: {
                    modifer: {
                        page: 'all',
                    }
                },
                
                   
               
            });

            var StartDateVal = document.getElementById("cphMain_HiddenStartDate").value;
            var EndDateVal = document.getElementById("cphMain_HiddenEndDate").value;

            $noCon('.datepicker').datepicker({
                autoclose: true,
                format: 'dd-mm-yyyy',
                timepicker: false,
                startDate: StartDateVal,
                endDate: EndDateVal,
            });


        });

        function LoadDropdowns(mode) {

            var orgID = '<%= Session["ORGID"] %>';
            var corptID = '<%= Session["CORPOFFICEID"] %>';
            var ReportId = document.getElementById("cphMain_hiddenReportId").value;

            var Elements = document.getElementsByClassName('clsDDl');
            var Dropdowns = "";

            for (var i = 0; Elements[i]; ++i) {

                var Value = "";
                var Id = Elements[i].id;
                if (mode != "0") {
                    Value = Elements[i].value;
                }

                if (Dropdowns == "") {
                    Dropdowns = Id + "–" + Value;
                }
                else {
                    Dropdowns += "¦" + Id + "–" + Value;
                }
            }

            if (Dropdowns != "") {

                $noCon.ajax({
                    async: false,
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    url: "Report_Builder.aspx/LoadFilterDropdownsWeb",
                    data: '{orgID: "' + orgID + '",corptID: "' + corptID + '",ReportID: "' + ReportId + '",Dropdwn: "' + Dropdowns + '"}',
                    dataType: "json",
                    success: function (data) {

                        var temp = new Array();
                        var temp = data.d;

                        var Elements = document.getElementsByClassName('clsDDl');

                        for (var i = 0; Elements[i]; ++i) {
                            if (temp[i] != null && temp[i] != undefined) {

                                var DDlData = temp[i].split('|')[0];
                                var ddlName = temp[i].split('|')[1];

                                $noCon("#" + ddlName).empty();
                                $noCon("#" + ddlName).append(DDlData);

                                var tempDrpdwnList = new Array();
                                var tempDrpdwnList = Dropdowns.split('¦');

                                for (a in tempDrpdwnList) {

                                    var tempDrpdwn = new Array();
                                    var tempDrpdwn = tempDrpdwnList[a].split('–');

                                    var drpdwnId = tempDrpdwn[0];
                                    var drpdwnVal = tempDrpdwn[1];

                                    if (ddlName == drpdwnId) {
                                        if (drpdwnVal != "") {
                                            var exists = 0 != $noCon('#' + ddlName + ' option[value=' + drpdwnVal + ']').length;
                                            if (exists == true) {
                                                $noCon("#" + ddlName).val(drpdwnVal);
                                            }
                                        }
                                    }
                                }
                            }
                        }


                    }
                });
            }

            if (mode == "0") {

                if (document.getElementById("cphMain_hiddenSearchField").value != "") {

                    var temp = new Array();
                    temp = document.getElementById("cphMain_hiddenSearchField").value.split('|');

                    for (a in temp) {
                        if (temp[a] != "") {

                            var tempSearch = new Array();
                            tempSearch = temp[a].split('‡');

                            for (i in tempSearch) {

                                var Type = tempSearch[0];
                                var Name = tempSearch[1];
                                var Value = tempSearch[2];

                                if (Value != "" && Value != null) {
                                    if (Type == "DDL" || Type == "TXT" || Type == "TXTDEC" || Type == "TXTNUM" || Type == "DATEPICK" || Type == "MNTH" || Type == "YEAR" || Type == "QUARTR" || Type == "HALFYR") {
                                        $noCon("#" + Name).val(Value);
                                    }
                                    else if (Type == "CBX" || Type == "RADIO") {
                                        if (Value == "1") {
                                            document.getElementById(Name).checked = true;
                                        }
                                        else {
                                            document.getElementById(Name).checked = false;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        function ChangeFilter(mode) {

            LoadDropdowns(mode);

            document.getElementById("cphMain_hiddenSearchField").value = "";

            $noCon(".col-sm-2").css("display", "block");

            if (document.getElementById("cphMain_hiddenDisplayArray").value != "") {

                var NoDisply = document.getElementById("cphMain_hiddenDisplayArray").value;

                var tempNoDisplArr = new Array();
                tempNoDisplArr = NoDisply.split('¦');

                if (document.getElementById("cphMain_hiddenFilterArray").value != "") {

                    var Filtrs = document.getElementById("cphMain_hiddenFilterArray").value;

                    var tempFilterArray = new Array();
                    tempFilterArray = Filtrs.split('¦');

                    for (var p = 0; p < tempFilterArray.length; p++) {

                        if (tempFilterArray[p] != "0") {//Filter array

                            var tempFilterArraySplit = new Array();
                            tempFilterArraySplit = tempFilterArray[p].split('—');

                            var Elemnt = tempFilterArraySplit[0];
                            var FilterArrayId = tempFilterArraySplit[2];
                            var FilterValue = document.getElementById(FilterArrayId).value;

                            GetDataControls(Elemnt, FilterArrayId, FilterValue);//set hidden Search field data


                            if (tempNoDisplArr[p] != "0") {//No display array

                                var tempNoDisplySplit = new Array();
                                tempNoDisplySplit = tempNoDisplArr[p].split('—');

                                for (a in tempNoDisplySplit) {
                                    if (tempNoDisplySplit[a] != "0") {

                                        var tempFilter = new Array();
                                        tempFilter = tempNoDisplySplit[a].split('^');

                                        for (z in tempFilter) {

                                            if (tempFilter[z] != "0") {
                                                var FilterId = tempFilter[z];
                                                if (z != 0) {
                                                    if (tempFilter[0] == FilterValue) {
                                                        document.getElementById("div" + FilterId).style.display = "none";
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        function GetDataControls(strType, strFilterName, Values) {

            if (document.getElementById("cphMain_hiddenSearchField").value == "") {
                document.getElementById("cphMain_hiddenSearchField").value = strType + "‡" + strFilterName + "‡" + Values;
            }
            else {
                document.getElementById("cphMain_hiddenSearchField").value = document.getElementById("cphMain_hiddenSearchField").value + "|" + strType + "‡" + strFilterName + "‡" + Values;
            }
        }


        function ChangeCheckbox(id) {
            if (document.getElementById(id).checked == true) {
                document.getElementById("hidden" + id).value = "1";
            }
            else {
                document.getElementById("hidden" + id).value = "0";
            }
        }

        function ChangeRadio(id) {
            if (document.getElementById(id).checked == true) {
                document.getElementById("hidden" + id).value = "1";
            }
            else {
                document.getElementById("hidden" + id).value = "0";
            }
        }

        function LoadSearch() {
            //alert(document.getElementById("cphMain_hiddenSearchField").value);
            if (document.getElementById("cphMain_hiddenSearchField").value != "") {

                var temp = new Array();
                temp = document.getElementById("cphMain_hiddenSearchField").value.split('|');

                for (a in temp) {
                    if (temp[a] != "") {

                        var tempSearch = new Array();
                        tempSearch = temp[a].split('‡');

                        for (i in tempSearch) {

                            var Type = tempSearch[0];
                            var Name = tempSearch[1];
                            var Value = tempSearch[2];

                            if (Value != "" && Value != null) {
                                if (Type == "DDL" || Type == "TXT" || Type == "TXTDEC" || Type == "TXTNUM" || Type == "DATEPICK" || Type == "MNTH" || Type == "YEAR" || Type == "QUARTR" || Type == "HALFYR") {
                                    $noCon("#" + Name).val(Value);
                                }
                                else if (Type == "CBX" || Type == "RADIO") {
                                    if (Value == "1") {
                                        document.getElementById(Name).checked = true;
                                    }
                                    else {
                                        document.getElementById(Name).checked = false;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        function LoadPrintFilters() {

            var FilterList = "";

            if (document.getElementById("cphMain_hiddenSearchFinal").value != "") {

                var Search = new Array();
                Search = document.getElementById("cphMain_hiddenSearchFinal").value.split('|');

                for (a in Search) {
                    if (Search[a] != "") {

                        field = Search[a].split('‡');

                        var Type = field[0];
                        var Name = field[1];
                        var Value = field[2];
                        var Text = "";

                        $noCon("#" + Name + ":visible").each(function () {

                            if (Value != "" && Value != null) {

                                var flag = "1";
                                var label = $noCon("#lbl" + Name).text().replace(/\*/g, '');

                                if (Type == "DDL" || Type == "MNTH" || Type == "YEAR" || Type == "QUARTR" || Type == "HALFYR") {
                                    if (Value == "0") {
                                        flag = "0";
                                    }
                                    else {
                                        var skillsSelect = document.getElementById(Name);
                                        Text = skillsSelect.options[skillsSelect.selectedIndex].text;

                                    }
                                }
                                else if (Type == "CBX" || Type == "RADIO") {
                                    flag = "0";
                                }
                                else if (Type == "TXT" || Type == "TXTDEC" || Type == "TXTNUM" || Type == "DATEPICK") {

                                    if (Value == "") {
                                        flag = "0";
                                    }
                                    else {
                                        Text = Value;
                                    }
                                }

                                if (flag == "1") {
                                    if (FilterList == "") {
                                        FilterList = label + " : " + Text;
                                    }
                                    else {
                                        FilterList += "$" + label + " : " + Text;
                                    }
                                }

                            }
                        });
                    }

                }

            }

            return FilterList;
        }


        function LinkClick(QueryString) {

            if (QueryString != "") {
                var nWindow = window.open(QueryString, 'PoP_Up', 'width=1199,height=500,left=70,top=100,directories=no,navigationbar=no,titlebar=no,toolbar=no,location=no,status=no,menubar=no,resizable=yes,scrollbars=yes');
                return false;
            }
        }

        function ValidateReport() {
            var ret = true;

            var Filtrs = document.getElementById("cphMain_hiddenFilterArray").value;
            var Datpckr = 0; var dDate = "";

            var tempFilterArray = new Array();
            tempFilterArray = Filtrs.split('¦');

            for (var p = 0; p < tempFilterArray.length; p++) {

                if (tempFilterArray[p] != "0") {//Filter array

                    var tempFilterArraySplit = new Array();
                    tempFilterArraySplit = tempFilterArray[p].split('—');

                    var Elemnt = tempFilterArraySplit[0];
                    var FilterArrayId = tempFilterArraySplit[2];
                    var FilterMndtry = tempFilterArraySplit[5];

                    $noCon("#" + FilterArrayId + ":visible").each(function () {

                        if (FilterMndtry == "1") {
                            if (document.getElementById(FilterArrayId).value == "") {
                                document.getElementById(FilterArrayId).style.borderColor = "Red";
                                document.getElementById(FilterArrayId).focus();
                                $noCon("#divWarning").html("Some of the information you entered is not correct or missing. Please check the highlighted fields below.");
                                $noCon("#divWarning").fadeTo(3000, 500).slideUp(500, function () {
                                });
                                ret = false;
                            }
                        }
                    });

                    if (ret == true) {

                        if (Elemnt == "DATEPICK") {//date validation

                            if (Datpckr > 0) {
                                if (dDate != "" && document.getElementById(FilterArrayId).value != "") {

                                    dDateTo = document.getElementById(FilterArrayId).value;
                                    var arrDateFromchk = dDate.split("-");
                                    DateFrom = new Date(arrDateFromchk[2], arrDateFromchk[1] - 1, arrDateFromchk[0]);
                                    var arrDateTochk = dDateTo.split("-");
                                    DateTo = new Date(arrDateTochk[2], arrDateTochk[1] - 1, arrDateTochk[0]);

                                    if (DateFrom > DateTo) {
                                        document.getElementById(FilterArrayId).style.borderColor = "Red";
                                        document.getElementById(FilterArrayId).focus();
                                        $noCon("#divWarning").html("From date cannot be greater than To date");
                                        $noCon("#divWarning").fadeTo(3000, 500).slideUp(500, function () {
                                        });
                                        ret = false;
                                    }
                                    else {
                                        dDate = document.getElementById(FilterArrayId).value;
                                    }

                                }
                            }
                            else {
                                dDate = document.getElementById(FilterArrayId).value;
                            }
                            Datpckr++;
                        }
                    }

                }
            }

            if (ret == true) {
                document.getElementById("cphMain_hiddenSearchFinal").value = document.getElementById("cphMain_hiddenSearchField").value;
            }
            return ret;
        }

        function DisableEnter(evt) {
            evt = (evt) ? evt : window.event;
            var keyCodes = evt.keyCode ? evt.keyCode : evt.which ? evt.which : evt.charCode;
            if (keyCodes == 13) {
                return false;
            }
        }
        function RemoveTag(control) {
            var text = document.getElementById(control).value;
            var replaceText1 = text.replace(/</g, "");
            var replaceText2 = replaceText1.replace(/>/g, "");
            document.getElementById(control).value = replaceText2;

            ChangeFilter(1);
        }
        function isTag(evt) {

            evt = (evt) ? evt : window.event;
            var keyCodes = evt.keyCode ? evt.keyCode : evt.which ? evt.which : evt.charCode;
            if (keyCodes == 13) {
                return false;
            }
            var charCode = (evt.which) ? evt.which : evt.keyCode;
            var ret = true;
            if (charCode == 60 || charCode == 62) {
                ret = false;
            }
            return ret;
        }

        function isNumber(evt) {
            evt = (evt) ? evt : window.event;
            var keyCodes = evt.keyCode ? evt.keyCode : evt.which ? evt.which : evt.charCode;
            var charCode = (evt.which) ? evt.which : evt.keyCode;
            //at enter
            if (keyCodes == 13) {
                return false;
            }
                //0-9
            else if (keyCodes >= 48 && keyCodes <= 57) {
                return true;
            }
                //numpad 0-9
            else if (keyCodes >= 96 && keyCodes <= 105) {
                return true;
            }
                //left arrow key,right arrow key,home,end ,delete
            else if (keyCodes == 37 || keyCodes == 39 || keyCodes == 36 || keyCodes == 35 || keyCodes == 46 || keyCodes == 38 || keyCodes == 40) {
                return true;

            }
            else {
                var ret = true;
                if (charCode > 31 && (charCode < 48 || charCode > 57)) {


                    ret = false;
                }
                return ret;
            }
        }

        function isDecimal(evt) {
            evt = (evt) ? evt : window.event;
            var keyCodes = evt.keyCode ? evt.keyCode : evt.which ? evt.which : evt.charCode;
            var charCode = (evt.which) ? evt.which : evt.keyCode;
            //at enter
            if (keyCodes == 13) {
                return false;
            }
                //0-9
            else if (keyCodes >= 48 && keyCodes <= 57) {
                return true;
            }
                //numpad 0-9
            else if (keyCodes >= 96 && keyCodes <= 105) {
                return true;
            }
                //left arrow key,right arrow key,home,end ,delete
            else if (keyCodes == 37 || keyCodes == 39 || keyCodes == 36 || keyCodes == 35 || keyCodes == 46 || keyCodes == 38 || keyCodes == 40 || keyCodes == 190 || keyCodes == 110) {
                return true;

            }
            else {
                var ret = true;
                if (charCode > 31 && (charCode < 48 || charCode > 57)) {
                    ret = false;
                }
                return ret;
            }
        }

        function BlurAmount(obj) {

            var decCnt = document.getElementById("<%=hiddenDecimalCount.ClientID%>").value;
            var RoundedOT = document.getElementById(obj).value.trim();
            if (RoundedOT.match(/^\d+(\.\d+)?$/)) {

                document.getElementById(obj).value = parseFloat(RoundedOT).toFixed(decCnt);
            }
            else {
                document.getElementById(obj).value = "";
            }

            ChangeFilter(1);
        }

        function BlurNotNumber(obj) {
            var txt = document.getElementById(obj).value;

            if (txt != "") {
                if (txt.indexOf('.') !== -1) {
                    document.getElementById(obj).value = "";
                    document.getElementById(obj).focus();
                    return false;
                }
                if (isNaN(txt)) {
                    document.getElementById(obj).value = "";
                    document.getElementById(obj).focus();
                    return false;

                }
                if (txt < 0) {
                    document.getElementById(obj).value = "";
                    document.getElementById(obj).focus();
                    return false;
                }

            }

            var text = document.getElementById(obj).value;
            var replaceText1 = text.replace(/</g, "");
            var replaceText2 = replaceText1.replace(/>/g, "");
            document.getElementById(obj).value = replaceText2;

            ChangeFilter(1);
        }

        function PrintClick(PrintMode) {

            var strPrintMode = PrintMode;
            var orgID = '<%= Session["ORGID"] %>';
            var corptID = '<%= Session["CORPOFFICEID"] %>';
            var ReportID = document.getElementById("<%=hiddenReportId.ClientID%>").value;
            var hiddenSearchField = document.getElementById("<%=hiddenSearchField.ClientID%>").value;
            var hiddenDisplayArray = document.getElementById("<%=hiddenFilterArray.ClientID%>").value;;
            var hiddenDisplay = document.getElementById("<%=hiddenDisplayArray.ClientID%>").value;
            var CurrencyID = document.getElementById("<%=hiddenDefaultCurrency.ClientID%>").value;
            var ControlType = "";
            var ControlID = "";
            var ControlValue = "";
            var FilterList = LoadPrintFilters();
            if (corptID != "" && corptID != null && orgID != "" && orgID != null) {
                $.ajax({
                    type: "POST",
                    async: false,
                    contentType: "application/json; charset=utf-8",
                    url: "Report_Builder.aspx/PrintList",
                    data: '{orgID: "' + orgID + '",corptID: "' + corptID + '",ReportID: "' + ReportID + '",hiddenSearchField: "' + hiddenSearchField + '",hiddenDisplayArray: "' + hiddenDisplayArray + '",hiddenDisplay: "' + hiddenDisplay + '",CurrencyID: "' + CurrencyID + '",FilterList: "' + FilterList + '",strPrintMode:"' + strPrintMode + '"}',
                    dataType: "json",
                    success: function (data) {
                        if (data.d != "") {
                            window.open(data.d, '_blank');
                        }
                        else {
                            Error();
                        }
                    }
                });
            }
            else {
                window.location = '/Security/Login.aspx';
            }
            return false;
        }

        function Error() {
            $noCon("#divWarning").html("Some error occured!");
            $noCon("#divWarning").fadeTo(3000, 500).slideUp(500, function () {
            });
            return false;
        }

    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphMain" runat="Server">
    <asp:HiddenField ID="hiddenReportId" runat="server" />
    <asp:HiddenField ID="hiddenDtActns" runat="server" />
    <asp:HiddenField ID="hiddenCancelPrimaryId" runat="server" />
    <asp:HiddenField ID="hiddenDecimalCount" runat="server" />
    <asp:HiddenField ID="hiddenSearchField" runat="server" />
    <asp:HiddenField ID="hiddenRowCnt" runat="server" />
    <asp:HiddenField ID="hiddenCorporateName" runat="server" />
    <asp:HiddenField ID="hiddenUsername" runat="server" />
    <asp:HiddenField ID="hiddenDate" runat="server" />
    <asp:HiddenField ID="hiddenTotalRows" runat="server" />
    <asp:HiddenField ID="hiddenDisplayArray" runat="server" />
    <asp:HiddenField ID="hiddenFilterArray" runat="server" />
    <asp:HiddenField ID="hiddenPageLoad" runat="server" />
    <asp:HiddenField ID="hiddenSearchFinal" runat="server" />
    <asp:HiddenField ID="HiddenStartDate" runat="server" />
    <asp:HiddenField ID="HiddenEndDate" runat="server" />
    <asp:HiddenField ID="hiddenStrId" runat="server" />
    <asp:HiddenField ID="HiddenFieldHeader" runat="server" />
    <asp:HiddenField ID="hiddenDefaultCurrency" runat="server" />

    <ol class="breadcrumb">
        <li><a id="aHome" runat="server" href="">Home</a></li>
        <li><a href="/Home/Compzit_Home/Compzit_Home_Finance.aspx">Finance Management</a></li>
        <li class="active" id="reportHead" runat="server">Suppiler Outstanding Report</li>
    </ol>
    <!---alert_message_section---->
    <div class="myAlert-top alert alert-success" id="success-alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> Changes completed succesfully
    </div>

    <div class="myAlert-bottom alert alert-danger" id="divWarning">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Danger!</strong> Request not completed
    </div>

    <div class="content_sec2 cont_contr">
        <div class="content_area_container cont_contr">
            <div class="content_box1 cont_contr">

                <h2 id="head" runat="server">Report</h2>
                <div id="spanHead" runat="server" style="display: none;"></div>

                <div id="divFilterList" runat="server"></div>

                <div class="fg5">
                    <label for="cphMain_btnSearch" class="fg2_la1 nbsp1">&nbsp;</label>
                    <asp:Button ID="btnSearch" runat="server" class="submit_ser" OnClientClick="return ValidateReport();" OnClick="btnSearch_Click" />
                </div>

                <div class="clearfix"></div>
                <div class="free_sp"></div>
                <div class="devider"></div>

                <div id="divReport" class="table_box tb_scr" runat="server">
                </div>

            </div>
        </div>
    </div>

    <div id="divPrint" style="display:none;">

    <button id="print" onclick="return PrintClick('pdf');" class="print_o" title="Print page">
        <i class="fa fa-print"></i>
    </button>

    <button id="csv" onclick="return PrintClick('csv');" title="CSV" class="imprt_o">
        <i class="fa fa-file-excel-o"></i>
    </button>

   </div>

    <style>
        .dt-buttons {
            margin-left: 14%;
        }

        .print_button {
            float: right;
            font-size: 15px;
            line-height: 1.5em;
            cursor: pointer;
        }

        @media print {
            .print_button {
                display: none;
            }
        }
    </style>

</asp:Content>

